defaultReportType: warning
targets:
  - reportType: error
    module: "Foundation"
    type: "URL"
    name: "init\\(string:\\)"
  - reportType: error
    module: "Foundation"
    type: "URL"
    name: "path$"
  - reportType: error
    module: "Foundation"
    type: "String"
    name: "init\\(data"
# onlyModules:
#   - RestrictCallCore
# excludeModules:
#   - restrict-call
excludedFiles:
  - ".*/DerivedData/.*"
